### ISSUE TITLE
decrypt shouldn't require sender

### ISSUE THREAD

**Issue by bulkypanda** [xckev/CipherBot#2]
if message was sent for someone, only they should be able to decrypt it without requiring sender.
if it wasn't sent for them, display an error or smth

**Comment by xckev** [comment]
okay buddy thats not how public key encryption works... u kinda need the other persons public key and you cant know that with just the ciphertext

**Comment by bulkypanda** [comment]
@xckev do you not store who the message was sent for? if not, whatever u said makes sense
